--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t emmaxyz/simple-web ."
      - "docker tag emmaxyz/simple-web emmaxyz/simple-web:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push emmaxyz/simple-web:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"emmaxyz\" --password=\"Ilovedeborah10\""
version: 0.1
